TSE Examples added (Allan Alvarado)
ni/nidaqmx-python pull request #190
Opened 2022-09-28 19:06 UTC by Cygnum16

These are examples created by different TSEs from NI.

2022-09-28 19:44 UTC, zhindes requested changes
I only reviewed one example. I assume most of my comments apply to all of them.

A few other things:
* remove the placeholder.txt files from your commit
* if you're going to add a directory hierarchy, please move the existing examples
* match the naming of the existing examples, e.g. `snake_case.py`

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> +Author: Andres Quesada
Everything in this repo should inherit the [LICENSE](https://github.com/ni/nidaqmx-python/blob/master/LICENSE). Let's remove these author/copyright blocks.

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> +def ConfigureSampleClkTiming(desiredFreq, sampsPerbuff, cyclesPerBuff, DAQmxTask,sampsPerCycle):
this function name isn't pythonic. can you make it `cfg_samp_clk_timing`?

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> +    DAQmxTask.timing.cfg_samp_clk_timing(desiredSampClkRate, sample_mode = AcquisitionType.CONTINUOUS)
`DAQmxTask` is a confusing name. I thought this was calling a static function on a class. Can you rename the variable `task` to match the rest of the program?

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> +def ConfigureSampleClkTiming(desiredFreq, sampsPerbuff, cyclesPerBuff, DAQmxTask,sampsPerCycle):
Same is true for all of these functions in all of these examples.

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> +        print("Generating Data")
you should tell them how to stop. it looks like ctrl+c?

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> + Instructions for Running:
These instructions sound like there is an interactive UI or something. Can you change the language to make it clear that they need to modify the code?

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> +  Outputs:
there are no outputs here...

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> +  phase = math.fmod(phase + frequency * 360 * numElements, 360)
nothing uses phase after this... what is this doing? was it meant to be in the loop?

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> +  if WaveformType =='Triangle':
Python has enums, you should use that

2022-09-28 19:44 UTC, zhindes commented on nidaqmx_examples/Analog_Generation/Current/Cont_Gen_Cur_Wfm-Int_Clk.py
> +
lots of empty lines

2022-09-30 13:52 UTC, Cygnum16 commented
Thank you for your input, Zach! I will check again all the examples with your feedback provided and once they are correct I will create the pull request again. 

Thank you again!

2023-08-08 01:10 UTC, zhindes commented
Closing due to inactivity

2023-08-08 01:10 UTC, closed without merging