Generate channel.py file
ni/nidaqmx-python pull request #224
Opened 2023-03-21 12:23 UTC by samchris007

### What does this Pull Request accomplish?
- Generates channel.py file using **channel.py.mako**
- Uses the metadata (**attributes,py**) from **PR:** https://github.com/ni/grpc-device-scrapigen/pull/148 to generate **channel.py**.
- The differences between the existing and the newly generated channel.py are
<html></head><body link="#0563C1" vlink="#954F72">

Current Name | Changed To
-- | --
description | chan_descr
sync_unlock_behavior | chan_sync_unlock_behavior
physical_channel | physical_chan_name

</body></html></div>
</body>
</html>

### Why should this Pull Request be merged?
Implements [Task 2316151](https://dev.azure.com/ni/DevCentral/_workitems/edit/2316151): Generate all the channel classes in task modules

2023-03-21 16:59 UTC, bkeryan requested changes

2023-03-21 18:28 UTC, zhindes requested changes
Nothing to add other than what Brad already pointed out. Remove the `chan_` prefix from the names. I think once that is done, we'll have no deprecations.

2023-03-21 18:28 UTC, zhindes commented on generated/nidaqmx/_task_modules/channels/channel.py
> +    def chan_descr(self):
I agree, `chan.type`, `chan.description`, etc. are preferable.

2023-03-22 13:41 UTC, samchris007 commented on generated/nidaqmx/_task_modules/channels/channel.py
> +    def chan_descr(self):
Got it. Removed prefix `chan_`

2023-03-22 15:27 UTC, zhindes approved these changes
I'll merge once Brad gives his approval

2023-03-22 20:22 UTC, merged