Generated Trigger class files
ni/nidaqmx-python pull request #234
Opened 2023-03-27 10:28 UTC by MounikaBattu17

**Why should this Pull Request be merged?**
- This PR generates triggering folder files (`arm_start_trigger.py`, `handshake_trigger.py`, `pause_trigger.py`, `reference_trigger.py`, `start_trigger.py`)

**What does this Pull Request accomplish?**
- This implements 
[Task 2316158](https://dev.azure.com/ni/DevCentral/_workitems/edit/2316158): generate the trigger related classes

2023-03-27 10:38 UTC, MounikaBattu17 commented
The differences in the generated trigger files given below:
- `arm_start_trigger.py`: `timescale` is changed to `time_timescale`
- `handshake_trigger.py`: No changes 
- `pause_trigger.py`:  No changes 
- `reference_trigger.py`:  No changes 
- `start_trigger.py`: `timescale` is changed to `time_timescale`

2023-03-27 15:44 UTC, zhindes requested changes

2023-03-27 16:01 UTC, MounikaBattu17 commented on generated/nidaqmx/_task_modules/triggering/start_trigger.py
> +    def timescale(self):
Updated naming change from timescale to time_timescale and removed the timescale in deprecation logic.

2023-03-27 20:29 UTC, bkeryan commented on src/codegen/utilities/attribute_helpers.py
> +                attribute_data["name"] = _strip_name(attribute_data["name"], class_name)
Also:
- The `Attribute` class does some name fixups

```
class Attribute:
    """Structure for storing attribute metadata from scrapigen."""
    ATTRIBUTE_CHANGE_SET = {
        "ai_custom_scale_name": "ai_custom_scale",
        "ao_custom_scale_name": "ao_custom_scale",
        "ci_custom_scale_name": "ci_custom_scale",
        "ci_dup_count_prevent": "ci_dup_count_prevention",
        "chan_descr": "description",
        "chan_sync_unlock_behavior": "sync_unlock_behavior",
        "chan_is_global": "is_global",
        "physical_chan_name": "physical_channel",
    }
```

- On further thought, those name fixups also belong in scrapigen

2023-03-28 13:27 UTC, zhindes requested changes
something weird is going on with the commits, rebase perhaps?

2023-03-28 13:27 UTC, zhindes commented on README.rst
> +software and hardware installation experience.
These changes are already in master... the diffs here are really strange. can you rebase your commits on top of the current master?

2023-03-28 13:27 UTC, zhindes commented on generated/nidaqmx/_task_modules/channels/ci_channel.py
> +    @property
These commits are also weird... the deprecations aren't valid. `ci_count_edges_count_reset_reset_cnt` still exists.

2023-03-28 13:28 UTC, zhindes commented on generated/nidaqmx/_task_modules/channels/ci_channel.py
> +    @property
Latest commits fix it, woo!

2023-03-28 13:28 UTC, zhindes commented on README.rst
> +software and hardware installation experience.
Latest commits fix it, woo!

2023-03-28 13:28 UTC, zhindes approved these changes

2023-03-28 13:32 UTC, MounikaBattu17 commented on src/codegen/utilities/attribute_helpers.py
> +                attribute_data["name"] = _strip_name(attribute_data["name"], class_name)
As suggested incorrect `python_description` will be fixed later. Created a [Technical Debt 2347643](https://dev.azure.com/ni/DevCentral/_workitems/edit/2347643): Fix incorrect "python_description" in attributes metadata to track this issue.

2023-03-28 20:53 UTC, bkeryan approved these changes

2023-03-29 04:33 UTC, MounikaBattu17 commented on src/codegen/utilities/attribute_helpers.py
> +                attribute_data["name"] = _strip_name(attribute_data["name"], class_name)
Resolving this conversion.

2023-03-29 04:34 UTC, MounikaBattu17 commented
@zhindes This PR has got required approvals. Kindly merge.

2023-03-29 14:45 UTC, zhindes commented
@MounikaBattu17 - merge conflict on ` src/codegen/metadata/script_info.py`

2023-03-29 15:02 UTC, MounikaBattu17 commented
> @MounikaBattu17 - merge conflict on ` src/codegen/metadata/script_info.py`

@zhindes  Resolved the merge conflicts. Please merge.

2023-03-29 15:04 UTC, merged