Fix hashing for task_handle in GrpcStubInterpreter
ni/nidaqmx-python pull request #353
Opened 2023-05-16 12:19 UTC by samchris007

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nidaqmx-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

The task created using the gRPC interpreter in nidaqmx is not hashable and currently throws an exception when trying to find the hash value of the task.
The fix has been done by adding hashing logic(`hash_task_sequence()`) in both gRPC and Library interpreters.

### Why should this Pull Request be merged?

Fixes [Bug 2388532](https://ni.visualstudio.com/DevCentral/_workitems/edit/2388532): The task created using grpc interpreter is non hashable

### What testing has been done?

Tested by removing `@pytest.mark.library_only` for test_case `test_hash_operations`

2023-05-16 15:12 UTC, bkeryan requested changes

2023-05-16 15:12 UTC, bkeryan commented on generated/nidaqmx/_task_modules/channels/channel.py
> +        return self._interpreter.hash_task_sequence((self._handle, frozenset(self.channel_names)))
The interpreter should only be responsible for hashing task handles, not sequences.
```suggestion
        return self._interpreter.hash_task_handle(self._handle) ^ hash(frozenset(self.channel_names)))
```

2023-05-16 15:12 UTC, bkeryan commented on generated/nidaqmx/_grpc_interpreter.py
> +        return hash(task_sequence.name)
The interpreter should only be responsible for hashing task handles, not sequences.
```suggestion
    def hash_task_handle(self, task_handle):
        return hash(task_handle.name)
```

2023-05-16 18:15 UTC, zhindes approved these changes

2023-05-17 18:38 UTC, bkeryan approved these changes

2023-05-18 12:42 UTC, merged