Test Fixes | Update the failing test with xfail
ni/nidaqmx-python pull request #361
Opened 2023-05-17 14:45 UTC by Sakthi-SM

**What does this PR accomplish?**
1. [Bug 2393811](https://dev.azure.com/ni/DevCentral/_workitems/edit/2393811): DAQmxGetLoggingFilePath returns kErrorNULLPtr (-200604) when 1st IVI dance call passes value=NULL
2. [Bug 2393824](https://dev.azure.com/ni/DevCentral/_workitems/edit/2393824): DAQmx read/write status properties return errors when called from C, Python, or grpc-device
There are totally 4 test cases that are failing in DAQmx as result of the above bugs in gRPC device. This PR marks all these tests with xfail tag.

**Why should this PR be merged?**
Updated the failing tests in `read_properties` and `write_properties` with the xfail tag and linked them with the appropriate bug.

2023-05-17 14:56 UTC, zhindes approved these changes

2023-05-17 14:57 UTC, zhindes commented
FYI @Sakthi-SM 

```
./tests/component/test_read_properties.py:124:5: BLK100 Black would make changes.
./tests/component/test_write_properties.py:88:5: BLK100 Black would make changes.
```

2023-05-17 18:15 UTC, bkeryan requested changes

2023-05-18 12:48 UTC, bkeryan approved these changes

2023-05-18 12:50 UTC, merged

2023-05-18 13:03 UTC, bkeryan commented
FYI @Sakthi-SM I updated these to use grpc_xfail: https://github.com/ni/nidaqmx-python/pull/366