fix: update write teds array grpc call to pass bytes
ni/nidaqmx-python pull request #386
Opened 2023-05-29 15:45 UTC by keer1111

- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nidaqmx-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Fix the write_to_teds_array grpc call to pass bytes as expected

### Why should this Pull Request be merged?

To fix - [Bug 2400963](https://dev.azure.com/ni/DevCentral/_workitems/edit/2400963): write_to_teds_with_array() errors with GrpcStubInterpreter

### What testing has been done?

The testing code snippet in the above bug item is run and grpc call throws meaningful error if TEDS is not configured.

2023-05-30 14:18 UTC, zhindes approved these changes

2023-05-30 14:22 UTC, bkeryan requested changes

2023-06-01 12:43 UTC, keer1111 commented on generated/nidaqmx/_grpc_interpreter.py
I tried using the 'VALUES_IN_TED' array (Please point out if this is not the right one) from the `test_physical_channel_properties` test file. But still getting `TEDS_SENSOR_NOT_DETECTED` since there is not configured TEDS sensor. (Is there a way to simulate this?)

In order to verify this test case, will it be possible to configure a TEDS sensor?

2023-06-01 19:34 UTC, bkeryan requested changes

2023-06-01 19:34 UTC, bkeryan commented on tests/component/system/test_physical_channel.py
> +def test__physical_channel__write_to_teds_from_array_with_invalid_stream__throws_data_error(
Move "invalid stream" to the given clause.

Correct terminology: "bitstream" not "stream")

This also applies to the other test cases.

`test___invalid_bitstream___write_to_teds_from_array___throws_data_error`
`test___invalid_file_path___write_to_teds_from_file___throws_data_error`

2023-06-01 19:34 UTC, bkeryan commented on tests/component/system/test_physical_channel.py
> +        phys_chan.write_to_teds_from_file()
FYI: I wonder why the file path is optional

Cc: @zhindes

2023-06-02 19:49 UTC, bkeryan approved these changes

2023-06-05 07:21 UTC, merged