Regenerate the gRPC stubs with latest DAQmx proto
ni/nidaqmx-python pull request #391
Opened 2023-06-01 16:17 UTC by Sakthi-SM

### What does this Pull Request accomplish?

The attributes with bitfield enums were placed under the wrong type during the proto file generation. This was fixed as part of https://github.com/ni/grpc-device/pull/934. This uses the latest `.proto` file and regenerates the gRPC stubs.
The corresponding failing test cases have also been marked with `xfail`.

### Why should this Pull Request be merged?

This fixes [Bug 2395661](https://dev.azure.com/ni/DevCentral/_workitems/edit/2395661): Attributes with bitfield enum are listed under the wrong type in DAQmx proto file

### What testing has been done?

The changes have been tested manually

2023-06-01 17:52 UTC, bkeryan requested changes

2023-06-01 17:52 UTC, bkeryan commented on generated/nidaqmx/_stubs/nidaqmx_pb2.py
In the affected tests, update the xfail reason to "Requires NI gRPC Device Server version 2.2 or later"

2023-06-01 17:52 UTC, bkeryan commented on src/codegen/protos/nidaqmx.proto
> -}
Your nidaqmx.proto is out of date. You need to merge main into your grpc-device branch and rebuild.

2023-06-02 14:49 UTC, zhindes approved these changes

2023-06-02 15:01 UTC, bkeryan approved these changes

2023-06-05 05:25 UTC, merged