Fix - get analog powerup states without output type
ni/nidaqmx-python pull request #405
Opened 2023-06-06 14:41 UTC by keer1111

- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nidaqmx-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR reroutes the get_analog_power_up_states without output type to get_analog_power_up_states with output type since the corresponding C call is deprecated.

### Why should this Pull Request be merged?

To fix: [Bug 2400919](https://dev.azure.com/ni/DevCentral/_workitems/edit/2400919): get_analog_power_up_states() (without output type) returns errors with both LibraryInterpreter and GrpcStubInterpreter

### What testing has been done?

Test case added

2023-06-06 14:44 UTC, zhindes approved these changes

2023-06-06 17:39 UTC, bkeryan requested changes

2023-06-06 17:39 UTC, bkeryan commented on src/codegen/templates/system/system.py.mako
> +        states, channel_types = self._interpreter.get_analog_power_up_states_with_output_type(flatten_channel_string(channel_names), len(channel_names))
I think you can replace the rest of this with `return self.get_analog_power_up_states_with_output_type(channel_names)`

2023-06-06 17:39 UTC, bkeryan commented on src/codegen/templates/system/system.py.mako
> +        states, channel_types = self._interpreter.get_analog_power_up_states_with_output_type(flatten_channel_string(channel_names), len(channel_names))
Please add a comment saying why this doesn't call get_analog_power_up_states.

2023-06-07 15:14 UTC, bkeryan approved these changes

2023-06-08 04:41 UTC, merged