Add support for WaitForValidTimestamp to nidaqmx-python
ni/nidaqmx-python pull request #479
Opened 2024-01-31 06:49 UTC by DeborahOoi96

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nidaqmx-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR adds Time Trigger API support for the following functions in nidaqmx-python:
[DAQmxWaitForValidTimestamp](https://dev.azure.com/ni/DevCentral/_git/ni-central?path=/src/daqmx/api/nicai/source/nicai/ctask.cpp&version=GC83afeb252672d4420622e056eb9aab8930cae7d6&line=1252&lineEnd=1252&lineStartColumn=23&lineEndColumn=49&lineStyle=plain&_a=contents)

### Why should this Pull Request be merged?

It provides support for WaitForValidTimestamp in python.

### What testing has been done?

Ran nidaqmx-python code generator and validated the API was generated correctly
All existing functional test passed.

2024-01-31 16:00 UTC, bkeryan requested changes

2024-01-31 16:00 UTC, bkeryan commented on generated/nidaqmx/_base_interpreter.py
Adding the function to the internal interpreter classes is the first step. The next step is to add methods or properties to the public API.

For each timestamp event, you should edit the corresponding class to add a `wait_for_valid_timestamp()` method or something similar. These methods will hardcode the timestamp event parameter.

These are the events:
```
class TimestampEvent(Enum):
    START_TRIGGER = 12491  #: Start Trigger timestamp.
    REFERENCE_TRIGGER = 12490  #: Reference Trigger timestamp.
    ARM_START_TRIGGER = 14641  #: Arm Start Trigger timestamp.
    FIRST_SAMPLE = 16130  #: First Sample timestamp.
```
so edit these classes:
- https://github.com/ni/nidaqmx-python/blob/master/generated/nidaqmx/_task_modules/triggering/start_trigger.py
- https://github.com/ni/nidaqmx-python/blob/master/generated/nidaqmx/_task_modules/triggering/reference_trigger.py
- https://github.com/ni/nidaqmx-python/blob/master/generated/nidaqmx/_task_modules/triggering/arm_start_trigger.py
- https://github.com/ni/nidaqmx-python/blob/master/generated/nidaqmx/_task_modules/timing.py -- this one is special: the method should be named something like wait_for_first_samp_timestamp

2024-01-31 16:12 UTC, bkeryan commented on generated/nidaqmx/_base_interpreter.py
(An alternative is to expose a single `wait_for_valid_timestamp()` method on the `Task` or `Timing` class and have the user pass in the timestamp event parameter, but I don't think this fits into the design of the Python trigger APIs as well.)

2024-01-31 16:18 UTC, zhindes reviewed
Brad got it all!

2024-02-08 09:42 UTC, DeborahOoi96 commented
Not done yet, only rebased so far but haven't addressed comments yet.

2024-02-16 10:40 UTC, DeborahOoi96 commented on generated/nidaqmx/_base_interpreter.py
It would be complicated to make this trigger-specific as the python class name for wait_for_valid_timestamp is `Task`. 

The slightly more straightforward approach, codegen-wise, would be to just proceed with your alternate suggestion and add a single method to Task class, and have the user pass in the timestamp event parameter.

It's still possible to make it trigger-specific as per your original suggestion, but in my opinion it would require a significant amount of changes to the codegen. I'm still working on this, haven't pushed my changes yet because it's still under progress. Just wondering if it would be worth all the effort to proceed with this way. What do you think?

2024-02-16 15:49 UTC, bkeryan commented on generated/nidaqmx/_base_interpreter.py
The easiest way to implement the trigger-specific approach is to set `'python_codegen_method': 'CustomCode',` and add a hand-written implementation to each trigger template.

I now see that the .NET API uses the alternate approach (`Task.WaitForValidTimestamp` is right next to `Task.WaitUntilDone`), so I guess the alternate approach is ok. @zhindes do you agree?

2024-02-16 16:53 UTC, zhindes approved these changes

2024-02-19 02:25 UTC, DeborahOoi96 commented on generated/nidaqmx/_base_interpreter.py
I have update it to be task-based

2024-02-19 21:00 UTC, bkeryan requested changes

2024-02-19 21:00 UTC, bkeryan commented on src/handwritten/task.py
> +        self._interpreter.wait_for_valid_timestamp(self._handle, timestamp_event, timeout)
The interpreter methods expect ints, not enums. A test would have caught this.
```suggestion
        self._interpreter.wait_for_valid_timestamp(self._handle, timestamp_event.value, timeout)
```

2024-02-20 16:02 UTC, maxxboehme approved these changes

2024-02-20 17:52 UTC, bkeryan approved these changes

2024-02-20 18:04 UTC, merged