Add Counter Stream Reader tests
ni/nidaqmx-python pull request #497
Opened 2024-02-16 21:32 UTC by zhindes

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nidaqmx-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This ensures we have a test per method within the Counter stream readers class. These tests use an onboard timebase of a real X Series to validate we get correct data from either the Python or underlying C bindings.

### Why should this Pull Request be merged?

This will give us confidence that we haven't broken anything as we refactor parts of the Python and driver stack.

### What testing has been done?

```
$ poetry run ni-python-styleguide fix tests && poetry run ni-python-styleguide lint tests && poetry run pytest -rsP -k test___counter
=============================== test session starts ===============================
platform win32 -- Python 3.10.10, pytest-7.4.2, pluggy-1.3.0
rootdir: C:\dev\nidaqmx-python
configfile: pyproject.toml
testpaths: tests
plugins: cov-4.1.0, mock-3.11.1
collected 1653 items / 1611 deselected / 42 selected

tests\acceptance\test_stream_readers.py .................................... [ 85%]
......                                                                       [100%]

===================================== PASSES ======================================
======================= 42 passed, 1611 deselected in 6.17s =======================
```

2024-02-16 23:18 UTC, bkeryan requested changes

2024-02-16 23:18 UTC, bkeryan commented on tests/acceptance/test_stream_readers.py
> +    high_ticks_dtype: numpy.generic,
I think the dtypes should be `numpy.typing.DTypeLike`

2024-02-16 23:18 UTC, bkeryan commented on tests/acceptance/test_stream_readers.py
Buffered pulse input supports multi-channel. Does the Python API support that? Do you have to reshape the NumPy array yourself?

In LV, there is a `Counter 2D DBL NChan NSamp` poly VI instance.
In C, the `numSampsPerChan` and `arraySizeInSamps` parameters are separate so that you can specify an array with more than one channel.

This seems like a missing API feature, so it's outside the scope of this PR.

2024-02-19 17:38 UTC, zhindes commented on tests/acceptance/test_stream_readers.py
Oh wow, I had forgotten about that. We also added multi-channel double reads for 9361 to do multiple duty-cycle reads in the same task. You're right that Python doesn't support multi-channel counters quite right. I think `task.read` probably works already for doubles, but not pulses. There isn't a `ChannelReader` variant that looks appropriate for any of that, though. #498 498

2024-02-19 17:52 UTC, bkeryan approved these changes

2024-02-19 17:53 UTC, merged