Refactor Task Internal Modules: Collections
ni/nidaqmx-python pull request #541
Opened 2024-03-15 01:52 UTC by charitylxy

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nidaqmx-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?
This PR aims to address issue brought up in https://github.com/ni/nidaqmx-python/issues/461:
- Currently, task subobject types are defined in internal modules contained in private `nidaqmx._task_modules` package.
- We want to turn `task.py` into a package and merge it with the internal modules contained in ` nidaqmx._task_modules`

Refactoring work will be split into 5 PRs:
- [x] Refactoring `_task.py` and `_in_stream.py` -  https://github.com/ni/nidaqmx-python/pull/534
- [x] Refactoring `_export_signal.py`, `_out_stream.py`, `_timing.py` - https://github.com/ni/nidaqmx-python/pull/539
- [x] **Refactoring collections: `_channel_collection.py`, `_ai_channel_collection.py`, `_ao_channel_collection.py`, `_ci_channel_collection.py`, `_co_channel_collection.py`, `_di_channel_collection.py`, `_do_channel_collection.py`**
- [ ] Refactoring channels: `_channel.py`, `_ai_channel.py`, `_ao_channel.py`, `_ci_channel.py`, `_co_channel.py`, `_di_channel.py`, `_do_channel.py` 
- [ ] Refactoring triggering: `_triggers.py`, `_arm_start_trigger.py`, `_handshake_trigger.py`, `_pause_trigger.py`, `_reference_trigger.py`, `_start_trigger.py`

### Why should this Pull Request be merged?
In this PR to address https://github.com/ni/nidaqmx-python/issues/461, following changes have been made: 
- Moved `collections` to `task` package and made its modules private.
- Added type hints for `xx_channels` in `_task.py`
- Documentation updated.

### What testing has been done?
Ran `poetry run pytest` and all tests passed.

2024-03-18 14:16 UTC, zhindes approved these changes
out of my element; I trust you and Brad :)

2024-03-18 22:06 UTC, bkeryan requested changes

2024-03-19 01:18 UTC, bkeryan commented on docs/channel_collection.rst
> +nidaqmx.task.collections
The updated docs look good.

2024-03-19 01:18 UTC, bkeryan approved these changes

2024-03-19 01:58 UTC, merged